### ISSUE TITLE
Possibility to hide label in 1D barcode

### ISSUE THREAD

**Issue by lowerends** [codeitnowin/barcode-generator#11]
Hi,
Thanks for this great package. 
Is there a way to hide the label (= the text under the barcode) from a 1D barcode? I can't seem to achieve it with the current available calls. Being able to hide the label would give extra possibilities to style and position the label with CSS.

Thanks for your feedback!

**Comment by codeitnowin** [comment]
Hi Lowerends,

Please try to add given line for hiding label.
```php
$barcode->setLabel("");
```

**Comment by lowerends** [comment]
Thanks for your feedback.
I've tried that and that doesn't seem to work unfortunately. I do agree that this would be a good way to hide the label from the generated barcode image.

**Comment by codeitnowin** [comment]
Can you please share the code which you have written to generate barcode.

**Comment by lowerends** [comment]
I'm using the example from the readme:
```
$barcode = new BarcodeGenerator();
$barcode->setText("00123456789012345675");
$barcode->setType(BarcodeGenerator::Gs1128);
$barcode->setLabel("");
$ssccBarcode = $barcode->generate();
```

This generates the following image:
![image](https://user-images.githubusercontent.com/6588791/40839547-5603988e-65a3-11e8-889a-261f71a39056.png)

**Comment by codeitnowin** [comment]
Somehow setLabel method was not working for Gs1128. I have updated code. You can take clone of the repository or download zip.

Also you can install through composer - composer require codeitnowin/barcode

Same code will work fine for hiding label or customising label.

**Comment by lowerends** [comment]
Thanks! I've tested it and it seems to be working great!
