### ISSUE TITLE
Adding some more dependencies

### ISSUE THREAD

**Issue by chez14** [codeitnowin/barcode-generator#14]
Defining dependencies to the `composer.json` just to make sure that all user have installed the php-gd extensions.

I've wasted my time to troubleshoot the code and realizing that what i miss is installing the GD extension in PHP, lol. I doubt the composer was the culprit at first, but it turned out that the composer didn't check that i haven't installed the GD.

What do you think if we try to add `ext-gd` on the dependencies list?

**Comment by codeitnowin** [comment]
Hi Chris,

I have updated requirement dependencies in composer.json and README file.
Now, whenever users will install the package and gd will not be enabled or installed, Composer will give an error.
