### ISSUE TITLE
Hidde number of "Code39Extended"

### ISSUE THREAD

**Issue by joanebrown** [codeitnowin/barcode-generator#2]
Hi,

   I use the next code to generate an Code39 Barcode:

            $barcode = new BarcodeGenerator();
            $barcode->setText("0123456789");
            $barcode->setType(BarcodeGenerator::Code39Extended);
            $barcode->setScale(2);
            $barcode->setThickness(15);

            $code = $barcode->generate();

But I'm wondering if Can I hide the number below the barcode?

Thanks for your amazing package :)

**Comment by codeitnowin** [comment]
Thanks for comment with great suggestion. Soon we will provide updated package with addition of such requirements.

**Comment by joanebrown** [comment]
Thank you! I Eager await the update.
It would also be nice if we can choose the color of the bar code :)

**Comment by codeitnowin** [comment]
Kindly use following settings for changing barcode color or background color.
```
$barcode->setForegroundColor('#FF0000');
$barcode->setBackgroundColor('#EEAAFF');
```
