### ISSUE TITLE
Call to undefined function CodeItNow\BarcodeBundle\Generator\imagettftext()'

### ISSUE THREAD

**Issue by sheyworth** [codeitnowin/barcode-generator#3]
Even after installing all gd, freetype, and image support, I still receive this issue locally. Mac Yosemite.

**Comment by akhtarhealthians** [comment]
Can you please share your code with me, It is working fine here as i tested.

**Comment by akhtarhealthians** [comment]
You also contact me on er.akhtarkhan@gmail.com

**Comment by sheyworth** [comment]
Email sent - from shane@blacktietoronto.ca - thank you sir. Looking forward to figuring this one out.

**Comment by nomoredistance** [comment]
This is because PHP **must** be compiled with freetype support (--with-freetype-dir=DIR ) in order for the function `imagettftext()` to exist.
