### ISSUE TITLE
Format error

### ISSUE THREAD

**Issue by WookPlay** [codeitnowin/barcode-generator#8]
Hello, I need to generate the following barcode:

**4157707266014651802001012603068039000000006377069620171215**

In `GS1-128` format.

But I get the following error:

> Error: Error in formatting, can not find an identifier.

I do not understand in what part the error is and how to solve it.

**Comment by codeitnowin** [comment]
Hi WookPlay,

I have recently released a new version 3.0.0 of the package. The issue related to an unknown identifier for barcode GS1-128 has been resolved.

You have to add 2 more lines to your code after updating you barcode package to version 3.0.0.
```php
$barcode->setText("4157707266014651802001012603068039000000006377069620171215");

$barcode->setType(BarcodeGenerator::Gs1128);

// allow length greater than 48 characters
$barcode->setNoLengthLimit(true);
// allow unknown identifier
$barcode->setAllowsUnknownIdentifier(true);
```
You can reinstall package by below command
`composer require codeitnowin/barcode:3.0.0`
