### ISSUE TITLE
Line break

### ISSUE THREAD

**Issue by smartrahat** [codeitnowin/barcode-generator#9]
Can I add line break in _setText()_?

**Comment by codeitnowin** [comment]
Hi Rahat,

Currently, you can add \n for a new line but it will also impact on the barcode. 

Can you please let me know in which barcode format you want to add the new line?

**Comment by smartrahat** [comment]
Thank you for quick reply.

I am using this code: 

```
        $qrCode = new QrCode();
        $qrCode
            ->setText('Line One Line Two Line Three')
            ->setSize(200)
            ->setPadding(10)
            ->setErrorCorrection('high')
            ->setForegroundColor(array('r' => 0, 'g' => 0, 'b' => 0, 'a' => 0))
            ->setBackgroundColor(array('r' => 255, 'g' => 255, 'b' => 255, 'a' => 0))
            ->setLabel('Sl. No. 501')
            ->setLabelFontSize(16)
            ->setImageType(QrCode::IMAGE_TYPE_PNG);
```

I want the result like this

```
Line One
Line Two
Line Three
```

**Comment by codeitnowin** [comment]
Hi Rahat,

You also can use \n in QR Code text. 
```php
$qrCode
    ->setText("QR code \nby \ncodeitnow.in")
```

**Comment by smartrahat** [comment]
Earlier I tried with the \n but it was not working. The problem is I was using single quotation (' ').

With double quotation (" ") it's working perfectly. 

Thank you very much for your assistance.

**Comment by codeitnowin** [comment]
Issue resolved. I'm closing this issue.
